config/routes.rb
Rails.application.routes.draw do
  resources :tweets

  # member do
  #   get "preview"

  # end

  # collection do
  #   get 'search'
  # end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

root "tweets#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord

        validates  :description,  presence: true ,
                length: {minimum:3}
        validates :username,  presence: true ,
                length: {minimum:3}                
 

    include PgSearch::Model
    pg_search_scope :search_full_text, 
            against: { 
                    description: 'A', 
                    id: 'B', 
                    }   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  include Pagy::Backend
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    # @tweets = Tweet.all
      @pagy, @tweets = pagy(Tweet.all)
      if params[:query_text].present?
        @tweets = @tweets.search_full_text(params[:query_text])
      end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

        respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet ha sido creado satisfactoriamente", 
        class:"col  border-white " }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet ha sido modificado satisfactoriamente", 
        class:"text-center bg-dange" }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy!

    respond_to do |format|
      format.html { redirect_to tweets_path, status: :see_other, notice: "Tweet ha sido eliminado.", 
      class:"text-center bg-dange" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    include Pagy::Frontend

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Desafio M5 D14 Twe" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

    <body class="bg-info">

      <div id= "titulo" class=" container card mb-0 align-between" style="">
        <div class=" row text-bg-primary  ">
          <div class="col-md-4  d-flex justify-content-left">
            <img src="https://tse1.mm.bing.net/th?id=OIP.9gxQQcv4k1RJ9mCP6qOPLwHaEK&pid=Api&P=0&h=180" 
            class="img-fluid rounded-start  " alt="imagen spea">
          </div>

          <div class="col-md-4 ">
              <div class="card-body">
                <h1 class="card-title text-center">Tweets </h1>
              </div>
          </div>
                  <div class="col-md-4  d-flex justify-content-end">
            <img src="https://tse1.mm.bing.net/th?id=OIP.9gxQQcv4k1RJ9mCP6qOPLwHaEK&pid=Api&P=0&h=180" 
            class="img-fluid rounded-start " alt="imagen spea">
          </div>

        </div>
      </div>

      <section id="detalle">
        <div   class = "container  bg-info-bg-subtle">
          <%= yield %>
        </div>
        </section>

      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
      <script src="https://kit.fontawesome.com/e8f733cf95.js" crossorigin="anonymous"></script>
 
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class = "container py-4  text-center text-white">    

          <div class="card bg-info border rounded-2 ">
              <p class="card-text bg-secondary "  >
                  <%= form.label :Descripcion,  class:"form-label" %>
                  <%= form.text_field :description,  class:"form-control height: 100px"  %>

                  <%= form.label :Username, class:"form-label" %>
                  <%= form.text_field :username,  class:"form-control"  %>
              </p>
          </div>
    </div>

  <div class = "bt-3 text-center">
    <%= form.submit "Crear / Actualizar" ,  class:  "btn btn-sm btn-primary" %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">


        <%# <p class = "text-white"> %>
          <%# <strong>Description dddd:</strong> %>
          <%# <%= tweet.description %>
        <%# </p> %>

        <%# <p class = "text-white"> %>
          <%# <strong>Username:</strong> %>
          <%# <%= tweet.username %> 
        <%# </p> %>


    <div class = "container py-4  text-center text-white ">     

          <div class="card border rounded-2">
              <strong class="bg-secondary d-flex justify-content-center"> Descripcion
              </strong>

              <div class = "text-black  d-flex justify-content-left"> 
                  <%= tweet.description %>
              </div>

              <strong class="bg-secondary">Username:</strong>
              <div class = "text-black d-flex justify-content-left"> 
                <%= tweet.username %>
              </div>
          </div>
    </div>


</div>

app/views/tweets/edit.html.erb
<% content_for :title, "Editing tweet" %>

<h3 class="my-3 text-center text-white">Editar tweet  <%= @tweet.id %></h3>

  <div class="col  border rounded-4">
    <%= render "form", tweet: @tweet %>
  </div>


<div class = "d-flex justify-content-evenly  ">
  <%= link_to "Ver tweet", @tweet, class: "btn btn-sm btn-success px-4" %>
  <%= link_to "Retornar a tweets", tweets_path , class: "btn btn-sm btn-secondary" %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Tweets" %>

       <div class="my-2 col-12 d-flex justify-content-between border rounded-4 ">

            <%= form_with url: tweets_path, method: :get do |form| %>
            <%= form.text_field :query_text, placeholder: "Buscador", value: params[:query_text], class: "border rounded-4 px-5"%>

              <div class= "btn btn-secondary  ">
                  <%= form.submit "Buscar", class:"btn btn-primary px-4" %>
              </div>
            <%end%>

            <div class="d-flex justify-content-end px-5 ">
                <%== pagy_bootstrap_nav(@pagy)%>
            </div>
      </div>

<table class="table table-striped mb-3">

  <thead >
    <tr  class= "bg-info border rounded-2  ">
      <th>ID</th>
      <th>Description</th>
      <th>UserName</th>
      <th>Acciones</th>
    </tr>
  </thead>

    <tbody class= "bg-white  border rounded-4">
        <% @tweets.each do |tweet| %>
          <tr>
              <td><%= tweet.id %></td>
              <td><%= tweet.description %></td>
               <td><%= tweet.username %></td>
               <td class="d-flex justify-content-between ">
                  <%= link_to "Ver  ", tweet, class: "btn btn-sm btn-success px-2"  %> 
                  <%= link_to "Editar", edit_tweet_path(tweet), class: "btn btn-sm btn-secondary"  %> 
                  <%= button_to "Eliminar", tweet, method: :delete,  class: "btn btn-sm btn-danger"  %> 
               </td>
          </tr>
        <% end %>
    </tbody>
</table>



<%# <div id="tweets"> %>
  <%# <% @tweets.each do |tweet| %> 
    <%# <%= render tweet %> 
    <%# <p> %>
      <%# <%= link_to "Show this tweet", tweet  %>
    <%# </p> %>
  <%# <% end  %>
<%# </div> %>

  <div class="my-3 col-12 d-flex justify-content-between  border rounded-2">
    <div class="btn  btn-secondary px-4">
        <%= link_to "New tweet", new_tweet_path, class:"btn btn-primary" %>
    </div>

    <div class = " d-flex justify-content-between px-5"  >
        <%== pagy_bootstrap_nav(@pagy) %>
    </div>
    

  </div> 

app/views/tweets/new.html.erb
<% content_for :title, "Nuevos tweet" %>

<h3 class="my-5 text-center">Ingrese su nuevo tweet </h3>

<%= render "form", tweet: @tweet %>

<br>

<div class= "text-center">
  <%= link_to "Retornar", tweets_path, class: "btn btn-sm btn-secondary" %>
</div>

app/views/tweets/show.html.erb
<p style="color: red " class = "text-center "><%= notice %></p>

<h3 class="my-5 text-center text-white">Revisar el tweet  <%= @tweet.id %>  </h3>



<div class = "row  text-center col border rounded-4  ">
    <%= render @tweet , class: "text-white"%>
</div>

        <div class = "d-flex justify-content-evenly  ">
            <%= link_to "Editar tweet", edit_tweet_path(@tweet), class: "btn btn-sm btn-success" %> 
            <%= link_to "Retornar", tweets_path, class: "btn btn-sm btn-secondary" %> 
            <%= button_to "Eliminar", @tweet, method: :delete, class: "btn btn-sm btn-danger" %>
        </div>